---
# **TODO** list :
#
# storage location: https://docs.docker.com/registry/deploying/#storage-customization or https://docs.docker.com/registry/configuration/#storage
# letsencrypt : https://docs.docker.com/registry/configuration/#letsencrypt https://docs.docker.com/registry/deploying/#support-for-lets-encrypt
# garbage collection : https://docs.docker.com/registry/garbage-collection/
# restrict access to authenticated? : https://docs.docker.com/registry/deploying/#restricting-access & https://docs.docker.com/registry/configuration/#auth
# mirror docker hub ? : https://docs.docker.com/registry/recipes/mirror/
# webhooks: https://docs.docker.com/registry/notifications/

- name: Copy Docker registry service file for systemd
  copy:
    src: docker-registry.service
    dest: /etc/systemd/system/docker-registry.service

- name: Create data directory
  file:
    path: /var/lib/docker-registry
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Pull registry image
  docker_image:
    name: "{%- if registry is defined %}{%- if registry.cache is defined %}{{ registry.cache }}/{% endif %}{% endif %}registry:2"
    state: present

- name: Ensure Docker registry service is started and enabled at boot.
  service:
    name: docker-registry
    enabled: yes
    state: started
    
- name: ensure that docker registry is cleaned
  cron:
    name: docker registry cleanup cron
    user: root
    # @ 02:00 Everyday
    weekday: "*"
    hour: 2
    minute: 0
    job: "docker exec docker-registry /bin/registry garbage-collect /etc/docker/registry/config.yml &> /dev/null"
    state: present    
