- name: gather consul-server ip address
  setup:
  delegate_facts: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['consul-server'] }}"

- name: Test reachability to consul-server (RPC)
  wait_for:
    host: "{{ hostvars[item].ansible_default_ipv4.address }}"
    port: 8300
    timeout: 5
  with_items: "{{ groups['consul-server'] }}"

# - name: gather docker-host ip address
#   setup:
#   delegate_facts: true
#   delegate_to: "{{ item }}"
#   with_items: "{{ groups['docker-host'] }}"

# - name: Test reachability to consul-client (LAN gossip)
#   wait_for:
#     host: "{{ hostvars[item].ansible_default_ipv4.address }}"
#     port: 8301
#     timeout: 5
#   with_items: "{{ groups['docker-host'] }}"

- name: Ensures /etc/consul.d/client/ dir exists
  file:
    path: /etc/consul.d/client
    state: directory
  notify: "restart consul-client"

- name: 'Create the config client'
  template:
    src: config-client.j2
    dest: /etc/consul.d/client/config-client.json
    owner: root
    group: root
    mode: 0644
  delegate_facts: true
  notify: "restart consul-client"

- name: 'Install systemd consul-client.service'
  template:
    src: consul-client.service.j2
    dest: /etc/systemd/system/consul-client.service
    owner: root
    group: root
    mode: 0644
  notify: "restart consul-client"

- name: "start consul-client"
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: consul-client.service
  changed_when: false

