all:
  children:
    docker-hosts:
      hosts:
        vm2.dev-comutitres.fr:
        vm3.dev-comutitres.fr:
        vm4.dev-comutitres.fr:
        vm6.dev-comutitres.fr:
    gitlab-hosts:
      hosts:
        vm4.dev-comutitres.fr:
            CI_GITLAB_HOST: gitlab.dev-comutitres.fr
            CI_REDIS_HOST: vm6.dev-comutitres.fr
            CI_REDIS_PORT: 6379
            CI_DB_ADAPTER: postgresql
            CI_DB_HOST: vm6.dev-comutitres.fr
            CI_DB_PORT: 5432
            CI_DB_NAME: gitlabhq
            CI_DB_USER: gitlab
            CI_DB_PASSWORD: passw0rd
            CI_DOMAIN_NAME: vm4.dev-comutitres.fr
            CI_GITLAB_SECRETS_DB_KEY_BASE: sie_phae1Mavomahthahxafivueraihu
            CI_GITLAB_SECRETS_SECRET_KEY_BASE: ru9Iesh!oopaedayeaghofuingaethungimaeyohyohmukewediewaeshovohtej
            CI_GITLAB_SECRETS_OTP_KEY_BASE: aeVi7ja.maquooliacolietevaloowahfohkaeviesaeshahfohfueneraseeyun
    gitlab-runner-hosts:
      hosts:
        vm3.dev-comutitres.fr:
            CI_SERVER_URL: https://gitlab.dev-comutitres.fr
            CI_ROOT_USERNAME: root
            CI_ROOT_PASSWORD: 5iveL!fe
    nginx-hosts:
      hosts:
        vm2.dev-comutitres.fr:
    postgresql-hosts:
      hosts:
        vm6.dev-comutitres.fr:
            CI_DB_NAME: gitlabhq
            CI_DB_USER: gitlab
            CI_DB_PASSWORD: passw0rd
    redis-hosts:
      hosts:
        vm6.dev-comutitres.fr:
    backup-hosts:
      hosts:
        vm2.dev-comutitres.fr:
        vm1.dev-comutitres.fr:

    subnet:
      hosts:
        vm1.dev-comutitres.fr:
          vps: vps494404.ovh.net
          ipv4: 51.254.213.188
          bastion: true
          type: ssd2
          name: vm1
          public_ssh: true
        vm2.dev-comutitres.fr:
          vps: vps503108.ovh.net
          ipv4: 217.182.206.140
          type: ssd1
          name: vm2
          trusted_ports: ["22/tcp"]
          public_ports: ["443/tcp", "80/tcp"]
        vm3.dev-comutitres.fr:
          vps: vps503106.ovh.net
          ipv4: 217.182.206.15
          type: ssd2
          name: vm3
        vm4.dev-comutitres.fr:
          vps: vps503114.ovh.net
          ipv4: 217.182.207.96
          type: ssd3
          name: vm4
          trusted_ports: ["22/tcp", "10443/tcp"]
          public_ports: ["10022/tcp", "80/tcp"]
        vm5.dev-comutitres.fr:
          vps: vps503105.ovh.net
          ipv4: 217.182.205.222
          type: ssd2
          name: vm5
        vm6.dev-comutitres.fr:
          vps: vps503107.ovh.net
          ipv4: 217.182.206.135
          type: ssd2
          name: vm6

  vars:
    users:
      - hugh
      - sylvain
      - arnauld
      - fabien
      - amin
      - rguichard
