all:
  children:
    subnet:
      hosts:
        vps502105.ovh.net:
          bastion: true
          trusted_ports: []
          public_ports: ["22/tcp"]
        vps502106.ovh.net:
          trusted_ports: ["22/tcp"]
          public_ports: ["80/tcp", "443/tcp"]
  
  vars:
    users:
      - arnauld
      - fabien
      - amin