---
module: ci-vec
datacenter: "ci-vec"

bastion_ip: 51.254.213.188
privatenetwork:
  vm1:
    vps: vps494404.ovh.net
    ipv4: 51.254.213.188
    type: ssd2
    name: vm1
  vm2:
    vps: vps503108.ovh.net
    ipv4: 217.182.206.140
    type: ssd1
    name: vm2
  vm3:
    vps: vps503106.ovh.net
    ipv4: 217.182.206.15
    type: ssd2
    name: vm3
  vm4:
    vps: vps503114.ovh.net
    ipv4: 217.182.207.96
    type: ssd3
    name: vm4
  vm5:
    vps: vps503105.ovh.net
    ipv4: 217.182.205.222
    type: ssd2
    name: vm5
  vm6:
    vps: vps503107.ovh.net
    ipv4: 217.182.206.135
    type: ssd2
    name: vm6


users:
  - hugh
  - sylvain
  - arnauld
  - fabien
  - amin
  - francois
