---
- name: start container
  become: yes
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    ports:
     - "3000:3000"
    env:
        INFLUXDB_ADMIN_ENABLED: true
        INFLUXDB_DATA_ENGINE: tsm1
        INFLUXDB_REPORTING_DISABLED: false
