---
- name: start container
  become: yes
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    ports:
     - "3000:3000"
    env:
     GF_INSTALL_PLUGINS='grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource,grafana-piechart-panel'
