- name: create config folder
  become: yes
  file:
    path: /volumes/postgresql/config
    state: directory

- name: copy config file
  become: yes
  copy:
    src: files/postgresql.conf
    dest: /volumes/postgresql/config
    
- name: create data folder
  become: yes
  file:
    path: /volumes/postgresql/data
    state: directory

- name: install container
  become: yes
  docker_container:
    name: gitlab-postgresql
    image: sameersbn/postgresql:9.6-2
    state: started
    ports:
     - "5432:5432"
    volumes:
      - /volumes/postgresql/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - /volumes/postgresql/data:/var/lib/postgresql
    env:
        DB_NAME: gitlabhq
        DB_USER: gitlab
        DB_PASS: passw0rd
        DB_EXTENSION: pg_trgm        