---
- name: create config folder
  file:
    path: /volumes/telegraf/config
    state: directory

- name: copy config file
  become: yes
  copy:
    src: files/telegraf.conf
    dest: /volumes/telegraf/config