- cron:
    name: cron hot backup
    user: robocop
    # @ 02:00 Everyday
    weekday: "*"
    hour: 2
    minute: 0
    job: "/bin/sh /backup/scripts/hot-backup.sh > /home/robocop/hot-backup.log"

- cron:
    name: cron cold backup
    user: robocop
    # @ 02:00 on Saturday
    weekday: "6"
    hour: 2
    minute: 0
    job: "/bin/sh /backup/scripts/cold-backup.sh > /home/robocop/cold-backup.log"

- name: cron copy renewed cert
  become: yes
  cron:
    user: root
    minute: 5
    hour: 0,12
    job: cp /etc/letsencrypt/live/vm4.dev-comutitres.fr/fullchain.pem /volumes/gitlab/data/certs/gitlab.cert

- name: cron copy renewed key
  become: yes
  cron:
    user: root
    minute: 5
    hour: 0,12
    job: cp /etc/letsencrypt/live/vm4.dev-comutitres.fr/privkey.pem /volumes/gitlab/data/certs/gitlab.key
