- cron:
    name: add cron for hot backup
    user: robocop
    # @ 02:00 Everyday
    weekday: "*"
    hour: 2
    minute: 0
    job: "/bin/sh /backup/scripts/hot-backup.sh > /home/robocop/hot-backup.log"
    
- cron:
    name: add cron for cold backup
    user: robocop
    # @ 02:00 on Saturday
    weekday: "6"
    hour: 2
    minute: 0
    job: "/bin/sh /backup/scripts/cold-backup.sh > /home/robocop/cold-backup.log"    