- name: install gitlab container
  become: yes
  docker_container:
    name: gitlab-ci
    image: sameersbn/gitlab:10.3.5
    state: started
    ports:
        - "10022:22"
        - "10443:443"
    volumes:
      - /volumes/gitlab/logs:/var/log/gitlab
      - /volumes/gitlab/data:/home/git/data
    env:
        GITLAB_HOST: "{{ ci_gitlab_host }}"
        REDIS_HOST: "{{ ci_redis_host }}"
        REDIS_PORT: "{{ ci_redis_port }}"
        DB_ADAPTER: "{{ ci_db_adapter }}"
        DB_HOST: "{{ ci_db_host }}"
        DB_PORT: "{{ ci_db_port }}"
        DB_NAME: "{{ ci_db_name }}"
        DB_USER: "{{ ci_db_user }}"
        DB_PASS: "{{ ci_db_password }}"
        GITLAB_SIGNUP_ENABLED: 'false'
        GITLAB_SECRETS_DB_KEY_BASE: "{{ ci_gitlab_secrets_db_key_base }}"
        GITLAB_SECRETS_SECRET_KEY_BASE: "{{ ci_gitlab_secrets_secret_key_base }}"
        GITLAB_SECRETS_OTP_KEY_BASE: "{{ ci_gitlab_secrets_otp_key_base }}"
        GITLAB_HTTPS: 'true'
