- name: create logs folder
  become: yes
  file:
    path: /volumes/gitlab/logs
    state: directory
    
- name: create data folder
  become: yes
  file:
    path: /volumes/gitlab/data
    state: directory

- name: Install gitlab container
  become: yes
  docker_container:
    name: gitlab-ci
    image: sameersbn/gitlab:10.3.3
    state: started
    ports:
        - "10022:22"
        - "10080:80"
        - "10443:443"
    volumes:
      - /volumes/gitlab/logs:/var/log/gitlab
      - /volumes/gitlab/data:/home/git/data
    env:
        GITLAB_HOST: gitlab.dev-comutitres.fr
        REDIS_HOST: vm6.dev-comutitres.fr
        REDIS_PORT: 6379
        DB_ADAPTER: postgresql
        DB_HOST: vm6.dev-comutitres.fr
        DB_PORT: 5432
        DB_NAME: gitlabhq
        DB_USER: gitlab
        DB_PASS: passw0rd
        GITLAB_SIGNUP_ENABLED: false
        GITLAB_SECRETS_DB_KEY_BASE: sie_phae1Mavomahthahxafivueraihu
        GITLAB_SECRETS_SECRET_KEY_BASE: ru9Iesh!oopaedayeaghofuingaethungimaeyohyohmukewediewaeshovohtej
        GITLAB_SECRETS_OTP_KEY_BASE: aeVi7ja.maquooliacolietevaloowahfohkaeviesaeshahfohfueneraseeyun