- name: create logs folder
  become: yes
  file:
    path: /volumes/gitlab/logs
    state: directory

- name: create data folder
  become: yes
  file:
    path: /volumes/gitlab/data
    state: directory

- name: create certs folder
  become: yes
  file:
    path: /volumes/gitlab/data/certs
    state: directory

- name: create backup scripts folder
  become: yes
  file:
    path: /backup/scripts
    state: directory

- name: generate cold backup script
  template:
    src: cold-backup.sh.j2
    dest: /backup/scripts/cold-backup.sh
    owner: robocop
    group: robocop
    mode: u=rwx,g=rx,o=rx

- name: generate cold restore script
  template:
    src: cold-restore.sh.j2
    dest: /backup/scripts/cold-restore.sh
    owner: robocop
    group: robocop
    mode: u=rwx,g=rx,o=rx

- name: copy backup scripts files
  become: yes
  copy:
    src: files/backup/
    owner: robocop
    group: robocop
    dest: /backup/scripts
    mode: u=rwx,g=rx,o=rx
