- name: create logs folder
  become: yes
  file:
    path: /volumes/gitlab/logs
    state: directory

- name: create data folder
  become: yes
  file:
    path: /volumes/gitlab/data
    state: directory

- name: create certbot generation folder
  become: yes
  file:
    path: /volumes/gitlab/data/certbot
    state: directory

- name: create backup scripts folder
  become: yes
  file:
    path: /backup/scripts
    state: directory
    
- name: copy backup scripts files
  become: yes
  copy:
    src: files/backup/
    dest: /backup/scripts
    mode: u=rwx,g=rx,o=rx