---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add {{ usernames }} users to wheel group
  user:
    name: "{{ item }}"
    groups: wheel
    append: yes
    state: present 
    createhome: yes
  with_items: "{{ usernames }}"

- name: Add SSH public keys
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '../pub_keys/{{ item }}.pub') }}"
  with_items: "{{ usernames }}"


