---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add {{ usernames }} users to wheel group
  user:
    name: "{{ item }}"
    groups: wheel
    append: yes
    state: present 
    createhome: yes
  with_items: "{{ usernames }}"

- name: Add SSH public keys
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '../pub_keys/{{ item }}.pub') }}"
  with_items: "{{ usernames }}"
  when: personal_pubkey|default(true)

- name: Generate ssh_keys for {{ usernames }} users
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    state: present 
  register: "user_ssh_keys"
  with_items: "{{ usernames }}"
  when: pubkey_generate|default(false)

#- name: Debug user_ssh_keys
#  debug:
#    msg: "{{ item['item'] }}"
#  with_items:
#    - "{{ user_ssh_keys.results }}"

- name: Copy generated pub_key for {{ usernames }} on {{ pubkey_install_hosts }}
  authorized_key:
    user: "{{ item[1].name }}"
    key: "{{ item[1].ssh_public_key }}"
  delegate_to: "{{ item[0] }}"
  with_nested: 
   - "{{ groups['subnet'] }}"
   - "{{ user_ssh_keys.results }}"
  when: pubkey_generate|default(false)



