- name: set concurrent option
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: ^concurrent =
    line: concurrent = {{ gitlab_runner_concurrent }}
    state: present

- name: create gitlab runner certs folder
  become: yes
  file:
    path: /etc/gitlab-runner/certs
    state: directory
    
- name: copy letsencrypt ca root certificate to runner certs directory
  become: yes
  copy:
    src: files/letsencrypt-root-ca.crt
    dest: /etc/gitlab-runner/certs/ca.crt