- name: Nexus data folder
  file:
    path: /volumes/nexus/data
    state: directory
    mode: 0200

- name: Install nexus container
  become: yes
  docker_container:
    name: nexus
    image: sonatype/nexus3
    state: started
    ports:
      - "{{ nexus_port }}:8081"
    volumes:
      - /volumes/nexus/data:/nexus-data
