- name: Install certbot
  yum: name=certbot state=latest
  become: yes

- name: certbot in standalone mode
  command: certbot certonly --standalone -m {{ contact_mail }} -d {{ domain_name }} -n -vvv --agree-tos
  register: certbot_output

- name: debug
  debug:
    var: certbot_output

- name: cron renew
  become: yes
  cron:
    minute: 0
    hour: 0,12
    user: root
    job: python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew --standalone -vvv
  when: not nginx

- name: cron renew
  become: yes
  cron:
    minute: 0
    hour: 0,12
    user: root
    job: python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew
  when: nginx
