- name: Install certbot
  yum: name=certbot state=latest
  become: yes
  when: $nginx == 'false'

- name: run Certbot
  command: sudo certbot certonly --standalone -m {{ contact_mail }} -d {{ domain_name }} -n -vvv --agree-tos
  when: $nginx == 'false'


- name: Install certbot-nginx
  yum: name=certbot-nginx state=latest
  become: yes
  when: $nginx == 'true'

- name: run Certbot-nginx
  command: sudo certbot certonly --installer nginx --pre-hook "nginx -s stop" --post-hook "nginx" --redirect --standalone -m {{ contact_mail }} -d {{ domain_name }} -n -vvv --agree-tos
  when: $nginx == 'true'

- name: cron renew
  become: yes
  cron:
    seconds: 0
    minute: 0
    hour: 0,12
    user: root
    job: python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew
