- name: add HTTP service
  become: yes
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: add HTTPS service
  become: yes
  firewalld:
    service: https
    permanent: true
    state: enabled

- name: Enable firewalld
  become: yes
  service: name=firewalld state=restarted enabled=yes
