- name: Ensures /etc/nomad.d/server/ dir exists
  file:
    path: /etc/nomad.d/server
    state: directory

- name: 'Create the config server'
  template:
    src: config-server.j2
    dest: /etc/nomad.d/server/config-server.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nomad

- name: 'Install systemd nomad-server.service'
  copy:
    src: nomad-server.service
    dest: /etc/systemd/system/nomad-server.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nomad

- name: 'Reload systemd  and start nomad-server'
  systemd:
    state: started
    daemon_reload: yes
    name: nomad-server.service
