- name: gather nomad-server ip address
  setup:
  delegate_facts: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nomad-server'] }}"
  
- name: Ensures /etc/nomad.d/client/ dir exists
  file:
    path: /etc/nomad.d/client
    state: directory

- name: 'Create the config client'
  template:
    src: config-client.j2
    dest: /etc/nomad.d/client/config-client.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nomad

- name: 'Install systemd nomad-client.service'
  copy:
    src: nomad-client.service
    dest: /etc/systemd/system/nomad-client.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nomad

- name: 'Reload systemd  and start nomad-client'
  systemd:
    state: started
    daemon_reload: yes
    name: nomad-client.service
