- name: create nginx folder sites-enabled config
  become: yes
  file:
    path: /conf/nginx/sites-enabled
    state: directory
    owner: data
    group: data
    mode: 0644

- name: create nginx folder sites-available config
  become: yes
  file:
    path: /conf/nginx/sites-available
    state: directory
    owner: data
    group: data
    mode: 0644

- name: create nginx log folder
  become: yes
  file:
    path: /conf/nginx/logs/gitlab
    state: directory
    owner: data
    group: data
    mode: 0644

- name: create nginx folder site config
  become: yes
  copy:
    src: files/sites-enabled/gitlab
    dest: /conf/nginx/sites-enabled/gitlab
    owner: data
    group: data
    mode: 0644

- name: copy nginx config
  become: yes
  copy:
    src: files/nginx.conf
    dest: /conf/nginx/nginx.conf
    owner: data
    group: data
    mode: 0644

- name: link between sites-available and sites-enabled
  become: yes
  file:
    dest: "/conf/nginx/sites-available/{{ item.site }}"
    src: "/conf/nginx/sites-enabled/{{ item.site }}"
    state: link
    owner: data
    group: data
  with_items:
    - { site: 'gitlab'}

- name: run nginx container
  become: yes
  docker_container:
    name: nginx
    image: nginx
    volumes:
      - /conf/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - /conf/nginx/sites-available:/etc/nginx/sites-available:ro
      - /conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /conf/nginx/logs:/var/log/nginx
    state: started
    ports:
      - "80:80"
