- name: install nginx
  become: yes
  yum: name=nginx state=latest
  become: yes

- name: create nginx folder site config
  become: yes
  file:
    path: /etc/nginx/{{ item }}
    state: directory
  with_items:
    - sites-available
    - sites-enabled

- name: create nginx sites log folders
  become: yes
  file:
    path: /var/log/nginx/{{ item }}
    state: directory
  with_items:
    - gitlab

- name: create nginx conf.d folder
  become: yes
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: copy nginx site config
  become: yes
  copy:
    src: files/sites-enabled/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
  with_items:
    - gitlab

- name: copy nginx config
  become: yes
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy nginx conf.d
  become: yes
  copy:
    src: files/default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: link between sites-available and sites-enabled
  become: yes
  file:
    src: "/etc/nginx/sites-enabled/{{ item }}"
    dest: "/etc/nginx/sites-available/{{ item }}"
    state: link
  with_items:
    - gitlab


- name: Ensure nginx is started and enabled at boot.
  become: yes
  systemd:
    name: nginx
    state: restarted
    enabled: yes
