- name: create docker image folder
  become: yes
  file:
    path: /volumes/gitlab-runner/docker-image
    state: directory

- name: copy docker image files
  become: yes
  copy:
    src: files/docker/
    dest: /volumes/gitlab-runner/docker-image

- name: build docker image
  docker_image:
     path: /volumes/gitlab-runner/docker-image
     name: comutitres/gitlab-runner-java-maven

- name: create certs folder
  become: yes
  file:
    path: /volumes/gitlab-runner/certs
    state: directory

- name: copy letsencrypt ca certificate
  become: yes
  copy:
    src: files/letsencrypt-ca.crt
    dest: /volumes/gitlab-runner/certs/ca.crt

- name: install container
  become: yes
  docker_container:
    name: gitlab-runner-java-maven
    image: comutitres/gitlab-runner-java-maven
    state: started
    volumes:
      - /volumes/gitlab-runner/certs:/etc/gitlab-runner/certs
    env:
        CI_SERVER_URL: "{{ ci_server_url }}"
        USERNAME: "{{ ci_root_username }}"
        PASSWORD: "{{ ci_root_password }}"
        RUNNER_NAME: "Docker Java Maven Runner"
        RUNNER_EXECUTOR: shell
        CI_SERVER_TLS_CA_FILE: /etc/gitlab-runner/certs/ca.crt
        RUNNER_TAG_LIST: "java maven"
        REGISTER_LOCKED: false
