- name: install nginx paquet
  become: yes
  yum:
    name: nginx
    state: latest

- name: create sites configuration folders
  become: yes
  file:
    path: /etc/nginx/{{ item }}
    state: directory
  with_items:
    - sites-available
    - sites-enabled

- name: create folders to sites log
  become: yes
  file:
    path: /var/log/nginx/{{ item }}
    state: directory
  with_items:
    - "{{ sites }}"

- name: create nginx conf.d folder
  become: yes
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: create acme challenge folder
  become: yes
  file:
    path: /var/run/acme/acme-challenge
    state: directory
  when: letsencrypt

- name: copy nginx config
  become: yes
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy nginx conf.d
  become: yes
  copy:
    src: files/default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: configure sites
  become: yes
  template:
    src: files/sites-enabled/{{ item.template | default('default-conf.j2') }}
    dest: /etc/nginx/sites-available/{{ item.name }}
  with_items:
    - "{{ sites }}"

- name: active sites (link between sites-available and sites-enabled)
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ item.name }}"
    dest: "/etc/nginx/sites-enabled/{{ item.name }}"
    state: link
  with_items:
    - "{{ sites }}"

- name: Ensure nginx is started and enabled at boot.
  become: yes
  systemd:
    name: nginx
    state: restarted
    enabled: yes
