---
- name: "yum repo for docker"
  yum_repository:
    name: centos-extra
    enabled: yes
    baseurl: http://mirror.centos.org/centos/7/extras/x86_64
    description: CentOS Extra

- name: "yum repo base centos"
  yum_repository:
    name: centos
    enabled: yes
    baseurl: http://mirror.centos.org/centos/7/os/x86_64
    description: CentOS Base

# Set docker storage before installation : the volume is created during docker installation
- name: "Set docker storage"
  template:
    src: docker-storage-setup.j2
    dest: /etc/sysconfig/docker-storage-setup

- name: install docker and cron from centos repo
  yum:
    name: docker, cronie
  environment: "{{ proxy_env }}"

- name: gather registry facts
  setup:
  delegate_facts: true
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['docker-registry'] }}"

- name: /etc/sysconfig/docker from template
  template:
    src: sysconfig.docker.j2
    dest: /etc/sysconfig/docker
  notify:
    - restart docker

- name: setup /etc/rsyslog.d/engine-docker.conf
  template:
    src: engine-docker.conf.j2
    dest: /etc/rsyslog.d/engine-docker.conf
  notify:
    - restart docker

- name: ensure that docker containers are cleaned
  cron:
    name: docker cleanup cron
    user: root
    # @ 04:00 Everyday
    weekday: "*"
    hour: 4
    minute: 0
    job: "docker system prune -f &> /dev/null"
    state: present

- name: Ensure Docker is started and enabled at boot.
  systemd:
    name: docker
    state: started
    enabled: yes
