---
- hosts: all

  tasks:
    - include_role:
        name: users_declaration
      vars:
        usernames: "{{ users }}"
        pubkey_generate: true
        pubkey_install_hosts: "{{ groups['subnet'] }}"
      when: bastion

    - include_role:
        name: users_declaration
      vars:
        usernames: "{{ users }}"
      when: not bastion
