---
- name: Deploy Docker hosts
  hosts: docker-host
  gather_facts: true
  roles:
    - role: docker/docker_host
      tags: docker_host
      when: use_docker_ce == false

- name: Deploy Docker CE hosts
  hosts: docker-host
  gather_facts: true
  roles:
    - role: docker/docker_ce_host
      tags: docker_host
      when: use_docker_ce == true

- name: Deploy Docker registry
  hosts: docker-registry
  gather_facts: true
  roles:
    - role: docker/docker_host
      tags: docker_host
      when: use_docker_ce == false
    - role: docker/docker_ce_host
      tags: docker_host
      when: use_docker_ce == true
    - role: docker/docker_registry
      tags: docker_registry
