---
- hosts: subnet

  vars:
    subnet_zone: "trusted"

  handlers:

    - name: reload firewalld
      command: firewall-cmd --reload

  tasks:

    - name: Declare hosts in {{ subnet_zone }} zone
      firewalld: 
        zone: "{{ subnet_zone }}"
        source: "{{ item }}"
        permanent: true
        state: enabled
      with_items: |
                    {{ groups['subnet'] 
                      | map('extract', hostvars, 'ansible_eth0') 
                      | map(attribute='ipv4') 
                      | map(attribute='address') 
                      | list }}
      notify:
        - reload firewalld

    - name: Declare {{ subnet_zone }} ports ({{ subnet_ports|default([ '22/tcp' ]) }})
      firewalld:
        zone: "{{ subnet_zone }}"
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - "{{ subnet_ports|default([ '22/tcp' ]) }}"
      notify:
        - reload firewalld

    - name: Make sure defaults services are disabled (one will use explicit port)
      firewalld:
        zone: public
        service: "{{ item }}"
        permanent: true
        state: disabled
      with_items:
        - ssh
        - dhcpv6-client
      notify:
        - reload firewalld

    - name: Make sure ssh service is disabled (one will use explicit port)
      firewalld:
        zone: public
        service: ssh
        permanent: true
        state: disabled
      notify:
        - reload firewalld


    - name: Declare 'public' ports ({{ public_ports|default([]) }})
      firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - "{{ public_ports|default([]) }}"
      notify:
        - reload firewalld


