---
- hosts: subnet
  vars:
    subnet_zone: "trusted"
  tasks:
    - name: Retrieve firewalld active zones
      block:
        - command: firewall-cmd --get-active-zones
          changed_when: false
          register: firewalld_active_zones
        - debug:
            var: firewalld_active_zones
        - set_fact:
            firewalld_active_zones_list: |
                                          {{ firewalld_active_zones.stdout
                                            | regex_findall('(?ms)^([^\s]+)') }}
        - debug:
            var: firewalld_active_zones_list

    - name: Retrieve firewalld public zone settings
      block:
        - command: firewall-cmd --zone=public --list-all
          changed_when: false
          register: firewalld_public_zone
        - debug:
            var: firewalld_public_zone

    - name: Retrieve firewalld {{ subnet_zone }} zone settings
      block:
        - command: "firewall-cmd --zone={{ subnet_zone }} --list-all"
          changed_when: false
          register: firewalld_subnet_zone
        - debug:
            var: firewalld_subnet_zone

    - name: Check that only {{ subnet_zone }} and 'public' are actives
      assert:
        that: 
          - "'public' in firewalld_active_zones_list"
          - "'{{ subnet_zone }}' in firewalld_active_zones_list"
          - "firewalld_active_zones_list|length == 2"

    - name: Collect undeclared ports in public zone
      block:
        - set_fact:
            undeclared_public_ports: |
                              {{ firewalld_public_zone.stdout
                                  | regex_findall('ports: (.+)') 
                                  | first
                                  | default("")
                                  | regex_findall('([^\s]+)') }}
        - debug:
            var: undeclared_public_ports
        - set_fact:
            # Remove declared ports from the list:
            # only unwanted ports will remain
            undeclared_public_ports: |
                              {{ undeclared_public_ports 
                                  | difference([ item ]) }}
          with_items:
            - "{{ public_ports }}"
        - debug:
            var: undeclared_public_ports

    - name: Check that only declared ports are activated in public zone
      assert:
        that: 
          - "undeclared_public_ports|length == 0"

    - name: Collected activated services
      block:
        - set_fact:
            undeclared_public_services: |
                              {{ firewalld_public_zone.stdout
                                  | regex_findall('services: (.+)')
                                  | first
                                  | default("")
                                  | regex_findall('([^\s]+)') }}
        - debug:
            var: undeclared_public_services

    - name: Check that no services are activated in public zone
      assert:
        that: 
            - "undeclared_public_services|length == 0"