---
- hosts: all
  tasks:
    - name: Disable firewalld
      systemd:
        name: firewalld
        enabled: no
        state: stopped
      failed_when: false

    - name: Retrieve v4 rules
      command: iptables -nL
      changed_when: false
      register: v4_rules

    - name: Debug v4 rules
      debug:
        msg: "{{ v4_rules.stdout_lines }}"

    - name: Enable ip forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - include_role:
        name: my_iptables2
      vars:
        v4_apply: true
        v4_configure: true
        v4_persist: true

    - name: Retrieve v4 rules afterwards
      command: iptables -nL
      changed_when: false
      register: v4_rules_afterwards

    - name: Debug v4 rules afterwards
      debug:
        msg: "{{ v4_rules_afterwards.stdout_lines }}"
