- name: Install Gitlab Runner
  hosts: gitlab-runner-hosts
  vars_prompt:
    - name: "CI_ROOT_USERNAME"
      prompt: "Gitlab admin username"
      confirm: no
      private: yes
    - name: "CI_ROOT_PASSWORD"
      prompt: "Gitlab admin password"
      confirm: no
      private: yes
  tasks:
    - include_role:
        name: runner_provision
      vars:
        ci_server_url: "{{ CI_SERVER_URL }}"
        ci_root_username: "{{ CI_ROOT_USERNAME }}"
        ci_root_password: "{{ CI_ROOT_PASSWORD }}"