- hosts: nginx-hosts
  vars_prompt:
    - name: "contact_mail_prompt"
      prompt: "Email contact to lets encrypt"
      confirm: yes
      private: yes

  tasks:
    - name: "enable ip forwarding"
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Ensure nginx is stopped
      become: yes
      systemd:
        name: nginx
        state: stopped

    - name: Open ports
      iptables:
        chain: INPUT
        action: insert
        destination_port: "{{ item }}"
        protocol: tcp
        state: present
        jump: ACCEPT
      with_items:
        - 80
        - 443

    - name: Generate certificates
      include_role:
        name: lets_encrypt
      with_items:
        - gitlab.dev-comutitres.fr
        - sonar.dev-comutitres.fr
        - nexus.dev-comutitres.fr
        - registry.dev-comutitres.fr
        - grafana.dev-comutitres.fr
      vars:
        contact_mail: "{{ contact_mail_prompt}}"
        domain_name: "{{ item }}"
        nginx: false
        firewalld: false

    - include_role:
        name: nginx_provision_uh
      vars:
        letsencrypt: true
        sites:
          - name: gitlab
            server_name: "gitlab.dev-comutitres.fr"
            upstream_url: "https://vm4.dev-comutitres.fr:10443"
            ssl_certificate: "/etc/letsencrypt/live/gitlab.dev-comutitres.fr-0001/cert.pem"
            ssl_certificate_key: "/etc/letsencrypt/live/gitlab.dev-comutitres.fr-0001/privkey.pem"
          - name: nexus
            server_name: "nexus.dev-comutitres.fr"
            upstream_url: "https://vm5.dev-comutitres.fr"
            ssl_certificate: "/etc/letsencrypt/live/nexus.dev-comutitres.fr/cert.pem"
            ssl_certificate_key: "/etc/letsencrypt/live/nexus.dev-comutitres.fr/privkey.pem"
            client_max_body_size: 200m
          - name: sonar
            server_name: "sonar.dev-comutitres.fr"
            upstream_url: "https://vm5.dev-comutitres.fr"
            ssl_certificate: "/etc/letsencrypt/live/sonar.dev-comutitres.fr/cert.pem"
            ssl_certificate_key: "/etc/letsencrypt/live/sonar.dev-comutitres.fr/privkey.pem"
          - name: docker-registry
            server_name: "registry.dev-comutitres.fr"
            upstream_url: "http://localhost:5000"
            ssl_certificate: "/etc/letsencrypt/live/registry.dev-comutitres.fr/cert.pem"
            ssl_certificate_key: "/etc/letsencrypt/live/registry.dev-comutitres.fr/privkey.pem"
            client_max_body_size: 1000m
          - name: grafana
            server_name: "grafana.dev-comutitres.fr"
            upstream_url: "http://vm6.dev-comutitres.fr:3000"
            ssl_certificate: "/etc/letsencrypt/live/grafana.dev-comutitres.fr/cert.pem"
            ssl_certificate_key: "/etc/letsencrypt/live/grafana.dev-comutitres.fr/privkey.pem"
    - name: register cron
      include_role:
        name: lets_encrypt
      vars:
        nginx: true
        firewalld: false
        cron_only: true
