- name: install telegraf-statsd
  hosts: telegraf-hosts
  roles:
    - role: supervision_provision/telegraf

- name: install influxdb
  hosts: influxdb-hosts
  roles:
    - role: supervision_provision/influxdb

- name: install grafana
  hosts: grafana-hosts
  roles:
    - role: supervision_provision/grafana