---
- hosts: nexus-hosts
  vars_prompt:
    - name: "contact_mail_prompt"
      prompt: "Email contact to lets encrypt"
      confirm: yes
      private: yes

  vars:
    SONAR_PORT: 9000
    NEXUS_PORT: 8081

  tasks:

    - include_role:
        name: nexus_provision
      vars:
        nexus_port: "{{ NEXUS_PORT }}"

    - include_role:
        name: sonar_provision
      vars:
        sonar_port: "{{ SONAR_PORT }}"
        sonar_jdbc_url: "jdbc:postgresql://{{ SONAR_DB_HOST }}/{{ SONAR_DB_NAME }}"
        sonar_jdbc_username: "{{ SONAR_DB_USERNAME }}"
        sonar_jdbc_password: "{{ SONAR_DB_PASSWORD }}"

    - name: Open ports
      block:
        - name: http
          iptables:
            chain: INPUT
            action: insert
            destination_port: 80
            protocol: tcp
            jump: ACCEPT
            state: present

        - name: https
          iptables:
            chain: INPUT
            action: insert
            destination_port: 443
            protocol: tcp
            jump: ACCEPT
            state: present

    - include_role:
        name: lets_encrypt
      vars:
        contact_mail: "{{ contact_mail_prompt }}"
        domain_name: vm5.dev-comutitres.fr
        nginx: false
        firewalld: false

    - include_role:
        name: nginx_provision_uh
      vars:
        letsencrypt: true
        sites:
          - name: nexus
            server_name: "vm5.dev-comutitres.fr"
            upstream_url: "http://localhost:{{ NEXUS_PORT }}"
            ssl_certificate: "/etc/letsencrypt/live/vm5.dev-comutitres.fr/cert.pem"
            ssl_certificate_key: "/etc/letsencrypt/live/vm5.dev-comutitres.fr/privkey.pem"
            client_max_body_size: 200m
          - name: sonar
            server_name: "sonar.dev-comutitres.fr"
            upstream_url: "http://localhost:{{ SONAR_PORT }}"
            ssl_certificate: "/etc/letsencrypt/live/vm5.dev-comutitres.fr/cert.pem"
            ssl_certificate_key: "/etc/letsencrypt/live/vm5.dev-comutitres.fr/privkey.pem"
