---
- hosts: all
  vars_prompt:
    - name: "root_new_password"
      prompt: "Root new password"
      confirm: yes
      private: yes
 
  tasks:
    - include_role:
        name: users_declaration
      vars:
        usernames: ["arnauld", "amin", "fabien"]

    - name: Change root password
      user:
        name: root
        password: "{{ root_new_password }}"

    - include_role:
        name: ssh_disable_root
 