---
- hosts: all
  vars_prompt:
    - name: "root_new_password"
      prompt: "Root new password"
      confirm: yes
      #private: yes
 
  roles:
    - {role: users_declaration, usernames: ["arnauld"]}
    - ssh_disable_root
 