---
- hosts: all

  gather_facts: yes
  tasks:

  - name: Gather the free disk space for each server
    shell: df -h
    register: result
  - name: Display the results
    debug: 
      msg: "{{ result.stdout_lines }}"

#  - debug: 
#      msg: "Memory {{ ansible_memory_mb }}"
  - debug: 
      msg: "RAM free {{ ansible_memory_mb.real.free }} / total: {{ ansible_memory_mb.real.total }}"
      
